spring:
  config:
    activate:
      on-profile: deploy
server:
  port: 7878
camel:
  springboot:
    routes-include-pattern: file:yaml/deployAgent/**/*.yaml
---
spring:
  config:
    activate:
      on-profile: if
server:
  port: 8787
camel:
  springboot:
    routes-include-pattern: file:yaml/ifAgent/**/*.yaml
---
# Logging
logging:
  level:
    root: info
    org.apache.kafka.clients.consumer.ConsumerConfig: warn
  logback:
    rollingpolicy:
      max-history: 90
  file:
    name: logs/${spring.config.activate.on-profile}.log

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
